### ISSUE TITLE
Design Requirements for Nox.UI

### ISSUE THREAD

**Issue by rochar** [NoxOrg/Nox.Ui#2]

**Comment by DanielHodgeGH** [comment]
Creating Tech requirements for Nox.UI based on current Nox.Solution YAML - will be used to handover to 3rd party company for Nox.UI component development

Currently covering NoxTypes:

- NoxTextInput
- NoxMoneyInput
- NoxNumberInput
- NoxListInput
- NoxCheckboxInput
- NoxButtonInput

Review meeting booked 19/06/23 to cover questions about Validation, Masks, Event, translation handling

Current Doc Link:
https://regusgroupservices-my.sharepoint.com/:p:/g/personal/daniel_hodge_iwgplc_com/EQqOUi06fLtBsYidJ-ALZyYBx2sMMffevrpv1KaCrxoIOA?e=VdpZgd

**Comment by DanielHodgeGH** [comment]
Feedback from Andre 16/6/23 - need to closely link list of NoxTypes UI examples to NoxType reference - Also on requirements doc link UI component input option definitions to src class - Nox.Types & Nox.Solution.Models for clarity

**Comment by DanielHodgeGH** [comment]
Feedback from Andre 05/7/23 - added comments to OneDrive PPT - need to update PPT then submit again for review
